### ISSUE TITLE
Find a new name

### ISSUE THREAD

**Issue by rickclephas** [rickclephas/KMP-ObservableViewModel#50]
Something without KMM because @hhariri doesn't like it 😜

**Comment by Reedyuk** [comment]
Probably will mean renaming the KMP-Coroutines too?

Just wondering maybe you could combine both projects together and rename as one? I would imagine most people are using both together.

Kotlin-ViewModel-LifeCycle ???

**Comment by rickclephas** [comment]
> Probably will mean renaming the KMP-Coroutines too?

Not really. The issue is with "KMM" which is [no longer used](https://blog.jetbrains.com/kotlin/2023/07/update-on-the-name-of-kotlin-multiplatform/), "KMP" is fine.

> Just wondering maybe you could combine both projects together and rename as one? I would imagine most people are using both together.

KMM-ViewModel indeed works best when combined with KMP-NativeCoroutines.
However KMP-NativeCoroutines supports a lot more use cases, so it wouldn't make sense to combine them.

**Comment by mtomczynski** [comment]
or simply KMP-ViewModel?

**Comment by rickclephas** [comment]
@mtomczynski yeah KMP-ViewModel would work.
But there is another library that uses that name, so I was hoping to come up with something different 😅

**Comment by GuilhE** [comment]
![imagem](https://github.com/rickclephas/KMM-ViewModel/assets/2677139/542e1c67-2f23-4aff-abdc-4c65b648cd43)

I really like this image from [Android Architecture UI Layer](https://developer.android.com/topic/architecture/ui-layer) so, how about `KMP-UIStateHolder`? Agnostic to both Android and iOS and just another name for ViewModel. My 2 cents 😇

**Comment by mtomczynski** [comment]
maybe KMP-NativeViewModel? It'd keep the ViewModel for discoverability and be similar to KMP-NativeCoroutines

**Comment by rickclephas** [comment]
KMM-ViewModel is [now](https://github.com/rickclephas/KMP-ObservableViewModel/releases/tag/v1.0.0-BETA-1) called KMP-ObservableViewModel! 🥳

**Comment by hhariri** [comment]
@rickclephas Thanks so much for doing this!
