### ISSUE TITLE
[INFO] - Google is migrating the ViewModel class to KMP

### ISSUE THREAD

**Issue by GuilhE** [rickclephas/KMP-ObservableViewModel#60]
Good news 😊 
https://android-review.googlesource.com/c/platform/frameworks/support/+/2965063

**Comment by rickclephas** [comment]
As of [1.0.0-BETA-1](https://github.com/rickclephas/KMP-ObservableViewModel/releases/tag/v1.0.0-BETA-1) the library uses the AndroidX ViewModel for all supported KMP targets.

**Comment by GuilhE** [comment]
Does it support Kotlin 2.0.0-RCX?
