### ISSUE TITLE
Cannot find type Kmp_observableviewmodel_coreViewModel in scope

### ISSUE THREAD

**Issue by StjepanMiske** [rickclephas/KMP-ObservableViewModel#72]
Hi,

I just created an empty Kotlin Multiplatform project and tried to implement your framework on iOS side and this is what I get when I implement extension that you described in the tutorial:

<img width="969" alt="Screenshot 2024-05-19 at 16 42 08" src="https://github.com/rickclephas/KMP-ObservableViewModel/assets/16018035/63defc19-96cf-42a1-8286-0ca9db7f96ef">

Why is this happening and how can it be fixed?
Thx

**Comment by rickclephas** [comment]
Hi, could you share the `build.gradle.kts` file of your `shared` Kotlin module?

**Comment by rickclephas** [comment]
It looks like you are missing the [Kotlin](https://github.com/rickclephas/KMP-ObservableViewModel?tab=readme-ov-file#kotlin) implementation:
```kotlin
kotlin {
    sourceSets {
        all {
            languageSettings.optIn("kotlinx.cinterop.ExperimentalForeignApi")
        }
        commonMain {
            dependencies {
                api("com.rickclephas.kmp:kmp-observableviewmodel-core:1.0.0-BETA-2")
            }
        }
    }
}
```

**Comment by rickclephas** [comment]
You'll only see the Kotlin declarations that are part of the public API of your shared module.
So before the `Kmp_observableviewmodel_coreViewModel` type becomes visible in Swift, you would also need to create a `ViewModel` in Kotlin.
Once you have a ViewModel both the ViewModel class and the `Kmp_observableviewmodel_coreViewModel` type should be visible from Swift.

**Comment by evansmj** [comment]
> You'll only see the Kotlin declarations that are part of the public API of your shared module. So before the `Kmp_observableviewmodel_coreViewModel` type becomes visible in Swift, you would also need to create a `ViewModel` in Kotlin. Once you have a ViewModel both the ViewModel class and the `Kmp_observableviewmodel_coreViewModel` type should be visible from Swift.

What do you mean by 'in kotlin'?  I've added a ViewModel in the shared code and even used it in Android, however I see the same import issue here.

**Comment by evansmj** [comment]
Oh it looks like I couldnt get the package to resolve through spm to github.  I cloned it locally and then it was able to resolve
