### ISSUE TITLE
 Cannot find type 'Kmp_observableviewmodel_coreViewModel' in scope error in Xcode

### ISSUE THREAD

**Issue by yassineAbou** [rickclephas/KMP-ObservableViewModel#73]
I added the Gradle dependencies for KMP-ObservableViewModel in Android Studio and included the rickclephas/KMP-ObservableViewModel.git package for Xcode. However, I have the error "Cannot find type 'Kmp_observableviewmodel_coreViewModel' in scope". How can I resolve this issue?
![Screenshot 2024-05-22 at 19 21 41](https://github.com/rickclephas/KMP-ObservableViewModel/assets/72861602/dce68ee6-fe77-463d-89b1-3a8752ce97c5)

**Comment by rickclephas** [comment]
Hi! Have you already created a ViewModel in Kotlin as well?

**Comment by yassineAbou** [comment]
no, I didn't create the ViewModel

**Comment by yassineAbou** [comment]
The problem was fixed. I forgot to include the Kotlin viewModel. Thanks for the help.

**Comment by mayank-ast** [comment]
Wow it worked after creating a Kotlin View Model
