### ISSUE TITLE
onReceive binding must conform to publisher

### ISSUE THREAD

**Issue by itstheceo** [rickclephas/KMP-ObservableViewModel#74]
I am migrating to a new version, seeing if can remove some of my prior glue code along the way. I am trying to use `onReceive` however getting the following error about conforming to Publisher. Previously I handled this by having a wrapper class which contained `@Published var` and used the `createPublisher(...)` convenience methods however I was hoping to get rid of this as it always felt hacky. Is there a better way of doing things? Inside `onReceive` I would check the state (sealed interface) and map into native SwiftUI properties accordingly.

Using `@ObservedViewModel var viewModel = SessionViewModel()` in my SwiftUI view.

![Screenshot 2024-06-10 at 10 50 38](https://github.com/rickclephas/KMP-ObservableViewModel/assets/5218201/6684d23e-5685-4680-a510-ac32c1c047e0)

The shared view model is setup like this:
```
class SessionViewModel() : ViewModel() {

    private var _effect = MutableStateFlow<Effect>(viewModelScope, Effect.Initial)
    private var _state = MutableStateFlow<State>(viewModelScope, State.Initial)

    @NativeCoroutinesState
    val state: StateFlow<State> = _state.asStateFlow()

    @NativeCoroutinesState
    val effect: StateFlow<Effect> = _effect.asStateFlow()

   ...
}
```

Hoping it's something simple I've just missed. Cheers!

**Comment by rickclephas** [comment]
Depending on your project requirements there are a couple of ways to solve this.
I guess the easiest would be to use `onChange` instead of `onReceive`.

Btw instead of creating a wrapper class you can also subclass the viewmodel in Swift.

**Comment by itstheceo** [comment]
`onChange` has a annoying requirement too, requiring conformance to Equatable. Tricky because using sealed interfaces for the State, I can't add extensions to them in Swift; `Extension of protocol 'SessionViewModelState' cannot have an inheritance clause`.

![Screenshot 2024-06-11 at 07 11 29](https://github.com/rickclephas/KMP-ObservableViewModel/assets/5218201/ea6dfd0f-c470-4564-9eab-25d77282684d)

Subclassing in Swift is an interesting idea; here's my wrapper class for reference, it works for all my view models as the state / effect inherit from a base interface from an abstract viewmodel class.

```
class KMPObservableViewModelPublisher<T: BaseViewModel>: ObservableObject {
  
  @Published var state: BaseViewModelState?
  @Published var effect: BaseViewModelEffect?
  
  private var viewModel: T?
  
  init(viewModel: T?) {
    guard let viewModel = viewModel else {
      return // swiftUI previews
    }
    self.viewModel = viewModel
    
    createPublisher(for: viewModel.stateFlow)
      .assertNoFailure()
      .assign(to: &$state)
    
    createPublisher(for: viewModel.effectFlow)
      .assertNoFailure()
      .assign(to: &$effect)
  }
  
  public func dispatch(action: BaseViewModelAction) {
    viewModel?.dispatch(action: action)
  }
}
```

Then for usage, it acts as a wrapper and exposes the published values straight from Kotlin.
```
@ObservedObject var viewModel = KMPObservableViewModelPublisher(viewModel: SessionViewModel())
```

It's got me thinking maybe there's a better approach for modelling UI state for kotlin multiplatform projects 🤔  I'll have a think but, will close this as no issue with the library just nice to have another set of eyes, thank you.

**Comment by itstheceo** [comment]
The `onReceive` stuff, and wrapper class is purely for mapping viewModel changes into native SwiftUI properties. On the Android side, the Kotlin viewmodels are consumed directly in composable functions. Is there much in the way of lifecycle management on the iOS side?

This viewModel is used for acquiring a session. A root view observes the state, handling swapping between sign in screen and the rest of the app when authenticated. The views on both Android and iOS are mostly only changing based on loading, or displaying an alert based on any emitted effects; errors during form validation, or from the network response.

I'll try to simplify things and do away with the sealed classes all together; having the viewModel expose a StateFlow for loading, and a StateFlow for error information, doing away with any wrappers / publishers.

**Comment by rickclephas** [comment]
> Is there much in the way of lifecycle management on the iOS side?

Not really. It's mainly making sure the viewmodel is cleared/the viewmodelscope is cancelled

> Edit: I am actively moving a lot of the code into multiplatform compose, however the sign in views are highly custom using native shaders for subtle background and blur effects. I anticipate they will remain native.

That's also a very nice use case. Let me know how that goes!

**Comment by rickclephas** [comment]
> I did wonder about the use case for a SwiftUI Binding into a child view however, maybe you have some thoughts? 

This can be achieved with `$viewModel.loading`.
The error message you are seeing is correct, only mutable properties can be used as bindings.

> Currently I use an `onChange` to map the `loading` flow into the `@State` property which then gets bound to the `@Binding` in the child view.

In that case the `loading` from the ViewModel isn't really the same as `isLoading`.
`isLoading` can be updated by the view itself (through the binding).
Such changes won't be reflected in the ViewModel.

Changing your `StateFlow` to a `MutableStateFlow` solves that and will allow you to use the property directly:
```kotlin
@NativeCoroutinesState
val loading: MutableStateFlow<Boolean> = _loading
```

```swift
SignInTextField(
  value: $username,
  isDisabled: $viewModel.loading,
  placeholder: "Username"
)
```

**Comment by itstheceo** [comment]
oh that's cool! 🚀  thanks!

**Comment by osrl** [comment]
hi @rickclephas I wanted to do something like this:
```
public val MyViewModel.loadingMutable: NativeFlow<Boolean>
    get() = loading.asNativeFlow(null)
```

 in my own code but it's not possible since there is no dependency. I tried to add 
 `implementation("com.rickclephas.kmp:kmp-nativecoroutines-core:1.0.0-ALPHA-32")` as a dependecy but it didn't work. is it possible to add it a a dependency?
